version: '3'
services:
    web:
        build:
            # where we want our files to be coming from for the container
            context: .
            dockerfile: Dockerfile.dev

        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        stdin_open: true

    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        #overrides default start command    
        command: ["npm", "run", "test"]
        stdin_open: true
